import Config from 'react-native-config';

const {
  API_URL,
  ACCOUNT_ID,
  API_VERSION,
  TMDB_API_KEY,
  TMDB_CAST_FOLDER,
  TMDB_IMAGE_DOMAIN,
  TMDB_POSTER_FOLDER,
  TMDB_THUMBNAIL_FOLDER,
  TMDB_READ_ACCESS_TOKEN,
} = Config;

export {
  API_URL,
  ACCOUNT_ID,
  API_VERSION,
  TMDB_API_KEY,
  TMDB_CAST_FOLDER,
  TMDB_IMAGE_DOMAIN,
  TMDB_POSTER_FOLDER,
  TMDB_THUMBNAIL_FOLDER,
  TMDB_READ_ACCESS_TOKEN,
};
